image: python:3

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

before_script:
  - pip install -U pip setuptools
  - pip install -r requirements.txt

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

stages:
  - test

test_job:
  stage: test
  script:
    - flake8
