image: python:3

before_script:
  - export PIP_CACHE_DIR=".pip-cache"
  - pip install --upgrade pip
  - pip install -r requirements.txt

cache:
  paths:
    - .pip-cache

stages:
  - test

test_job:
  stage: test
  script:
    - flake8
