image: python:3

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

before_script:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - mkdir -p ~/.ssh
  - echo "$DOKKU_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'mars.ais.cmc.osaka-u.ac.jp' >> ~/.ssh/known_hosts

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

stages:
  - test
  - deploy

check_style:
  stage: test
  script:
    - flake8

deploy_to_dokku:
  stage: deploy
  environment:
    name: staging
    url: http://seot-staging.mars.ais.cmc.osaka-u.ac.jp
  script:
    - git push dokku@mars.ais.cmc.osaka-u.ac.jp:seot-staging $CI_BUILD_REF:master
  only:
    - master
