image: python:3

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

stages:
  - test
  - deploy

check_style:
  stage: test
  script:
    - pip install -r requirements.txt
    - flake8

check_migrations:
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py makemigrations --check

deploy_development:
  stage: deploy
  environment:
    name: development
    url: http://seot-dev.mars.ais.cmc.osaka-u.ac.jp
  script:
    - mkdir -p ~/.ssh
    - echo "$DOKKU_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 'mars.ais.cmc.osaka-u.ac.jp' >> ~/.ssh/known_hosts
    - git push -f dokku@mars.ais.cmc.osaka-u.ac.jp:seot-staging $CI_BUILD_REF:master
  only:
    - develop

deploy_production:
  stage: deploy
  environment:
    name: production
    url: http://seot.mars.ais.cmc.osaka-u.ac.jp
  script:
    - mkdir -p ~/.ssh
    - echo "$DOKKU_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 'mars.ais.cmc.osaka-u.ac.jp' >> ~/.ssh/known_hosts
    - git push -f dokku@mars.ais.cmc.osaka-u.ac.jp:seot-staging $CI_BUILD_REF:master
  only:
    - master
