# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 05:32
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_type',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='owner',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='agent',
            name='device_type',
            field=models.CharField(default='sensor', max_length=32),
        ),
        migrations.AddField(
            model_name='agent',
            name='dpp_listen_port',
            field=models.IntegerField(default=51423),
        ),
        migrations.AddField(
            model_name='agent',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='user_id',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='app',
            name='app_id',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='agent',
            name='capability',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='agent',
            name='in_use',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='agent',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
