# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='next_nodes',
            field=models.ManyToManyField(blank=True, null=True, related_name='_node_next_nodes_+', to='server.Node'),
        ),
    ]
