# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20161018_0532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='in_use',
            new_name='busy',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='agent',
            name='nodes',
            field=models.CharField(default='', max_length=256),
        ),
    ]
