# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20161109_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('job_id', models.CharField(max_length=256)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='server.App')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('args', models.CharField(default='', max_length=256)),
                ('to', models.CharField(default='', max_length=256)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='server.Job')),
            ],
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='nodes',
        ),
        migrations.AddField(
            model_name='nodetype',
            name='agents',
            field=models.ManyToManyField(related_name='nodes', to='server.Agent'),
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='server.NodeType'),
        ),
    ]
