# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20161125_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='application',
        ),
        migrations.AddField(
            model_name='job',
            name='application_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
