# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20170206_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='args',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
