# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20161125_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='agents',
            field=models.ManyToManyField(blank=True, null=True, related_name='nodes', to='server.Agent'),
        ),
    ]
