# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20170207_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='busy',
        ),
        migrations.RemoveField(
            model_name='node',
            name='running',
        ),
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.IntegerField(choices=[(1, 'idle'), (2, 'launching'), (3, 'running'), (4, 'stopping')], default=1, verbose_name='App Status'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'idle'), (2, 'accept_pending'), (3, 'running'), (4, 'stop_pending')], default=1, verbose_name='Job Status'),
        ),
    ]
