# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20161125_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodetype',
            name='agents',
        ),
        migrations.AddField(
            model_name='agent',
            name='nodes',
            field=models.ManyToManyField(related_name='agents', to='server.NodeType'),
        ),
    ]
