# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20161125_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='nodes',
            new_name='available_node_types',
        ),
    ]
