# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0008_auto_20161125_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='node',
            name='to',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='agent',
            name='ip_addr',
            field=models.CharField(default='127.0.0.1', max_length=64),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='server.User'),
        ),
        migrations.AddField(
            model_name='app',
            name='define_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/app_define_files/'),
        ),
        migrations.AddField(
            model_name='app',
            name='hold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='app',
            name='status',
            field=models.IntegerField(choices=[(1, 'idle'), (2, 'running'), (3, 'stopped')], default=1, verbose_name='App Status'),
        ),
        migrations.AddField(
            model_name='app',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='server.User'),
        ),
        migrations.AddField(
            model_name='job',
            name='allocated_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_jobs', to='server.Agent'),
        ),
        migrations.AddField(
            model_name='job',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='server.App'),
        ),
        migrations.AddField(
            model_name='node',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='server.App'),
        ),
        migrations.AddField(
            model_name='node',
            name='next_nodes',
            field=models.ManyToManyField(blank=True, related_name='_node_next_nodes_+', to='server.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='server.Job'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='server.NodeType'),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
