# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20170209_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hostname',
            field=models.CharField(default='agent', max_length=128),
        ),
    ]
