# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_agent_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='automatically_added',
            field=models.BooleanField(default='False'),
        ),
    ]
