# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_agent_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
