# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_node_automatically_added'),
        ('server', '0010_agent_active'),
    ]

    operations = [
    ]
